### ISSUE TITLE
vshadowmount segfault

### ISSUE THREAD

**Issue by ktwombley** [libyal/libvshadow#5]
Using vshadowmount included via SANS's SIFT workstation I get a segfault when attempting to access a volume shadow copy. vshadowmount works, and I can even losetup the resulting vss1, etc. files, but when I try to do anything more complicated than a plain `ls` on them (say, actually mounting the /dev/loopN) I get a segfault.

The disk image is taken from a windows 8.1 machine (CurrentVersion : 6.3). I am not sure if the issue is related to Win 8.1 disk images specifically. I haven't tested with a win7 or win10 image yet. When I get a chance I can update this issue once I test with more images.

Here is the version of vshadowmount and libvshadow

```
root@siftotron:/mnt/DFIR/win81# vshadowmount -V
vshadowmount 20160110

Copyright (C) 2011-2016, Joachim Metz.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Report bugs to <joachim.metz@gmail.com>.

root@siftotron:/mnt/DFIR/win81# file /usr/lib/libvshadow.so.1.0.0
/usr/lib/libvshadow.so.1.0.0: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c2ad89c9acd48894c7708fa041cbf6061701598b, stripped
```

Here's a typescript of the steps I took to create the issue, as well as the backtrace.

```
root@siftotron:/mnt/DFIR/win81# mmls hdd.raw
GUID Partition Table (EFI)
Offset Sector: 0
Units are in 512-byte sectors

      Slot      Start        End          Length       Description
000:  Meta      0000000000   0000000000   0000000001   Safety Table
001:  -------   0000000000   0000002047   0000002048   Unallocated
002:  Meta      0000000001   0000000001   0000000001   GPT Header
003:  Meta      0000000002   0000000033   0000000032   Partition Table
004:  000       0000002048   0000821247   0000819200   Basic data partition
005:  001       0000821248   0001353727   0000532480   EFI system partition
006:  002       0001353728   0001615871   0000262144   Microsoft reserved partition
007:  003       0001615872   0921436159   0919820288   Basic data partition
008:  004       0921436160   0922357759   0000921600
009:  005       0922357760   0976764927   0054407168   Basic data partition
010:  -------   0976764928   0976773167   0000008240   Unallocated

root@siftotron:/mnt/DFIR/win81# mkdir /mnt/vssmount

root@siftotron:/mnt/DFIR/win81# vshadowmount -o $((512*1615872)) /mnt/DFIR/win81/hdd.raw /mnt/vssmount/
vshadowmount 20160110

root@siftotron:/mnt/DFIR/win81# ls -al /mnt/vssmount/
total 4
dr-xr-xr-x  2 root root            0 Apr 20 04:17 .
drwxr-xr-x 24 root root         4096 Apr 20 04:17 ..
-r--r--r--  1 root root 470947987456 Jan  1  1970 vss1
-r--r--r--  1 root root 470947987456 Jan  1  1970 vss2
root@siftotron:/mnt/DFIR/win81# losetup -a
/dev/loop0: [fd01]:2229319 (/dev/loop0)
/dev/loop1: [fd01]:2229320 (/dev/loop1)
root@siftotron:/mnt/DFIR/win81# losetup -f /mnt/vssmount/vss1
root@siftotron:/mnt/DFIR/win81# losetup -a
/dev/loop0: [fd01]:2229319 (/dev/loop0)
/dev/loop1: [fd01]:2229320 (/dev/loop1)
loop: can't get info on device /dev/loop2: Transport endpoint is not connected
root@siftotron:/mnt/DFIR/win81# ls -al /core
-rw------- 1 root root 13721600 Apr 20 04:18 /core
root@siftotron:/mnt/DFIR/win81# date
Wed Apr 20 04:18:46 UTC 2016
root@siftotron:/mnt/DFIR/win81# mv /core ./vshadowmount.core
root@siftotron:/mnt/DFIR/win81# which vshadowmount
/usr/bin/vshadowmount
root@siftotron:/mnt/DFIR/win81# gdb /usr/bin/vshadowmount ./vshadowmount.core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/vshadowmount...done.
[New LWP 3354]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `vshadowmount -o 827326464 /mnt/DFIR/win81/hdd.raw /mnt/vssmount/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa1bb418935 in libcdata_btree_replace_value () from /usr/lib/libvshadow.so.1
(gdb) bt full
#0  0x00007fa1bb418935 in libcdata_btree_replace_value () from /usr/lib/libvshadow.so.1
No symbol table info available.
#1  0x00007fa1bb404078 in libvshadow_block_tree_insert () from /usr/lib/libvshadow.so.1
No symbol table info available.
#2  0x00007fa1bb40ae6b in libvshadow_store_descriptor_read_store_block_list ()
   from /usr/lib/libvshadow.so.1
No symbol table info available.
#3  0x00007fa1bb40b56f in libvshadow_store_descriptor_read_block_descriptors ()
   from /usr/lib/libvshadow.so.1
No symbol table info available.
#4  0x00007fa1bb40b87e in libvshadow_store_descriptor_read_buffer () from /usr/lib/libvshadow.so.1
No symbol table info available.
#5  0x00007fa1bb40661e in libvshadow_internal_store_read_buffer_from_file_io_handle ()
   from /usr/lib/libvshadow.so.1
No symbol table info available.
#6  0x00007fa1bb40676d in libvshadow_store_read_buffer () from /usr/lib/libvshadow.so.1
No symbol table info available.
#7  0x0000000000414562 in mount_handle_read_buffer (mount_handle=0x209c060, store_index=0,
    buffer=0x209cde0 "\270n\033\273\241\177", size=4096, error=0x7ffe74bfd0b8) at mount_handle.c:585
        function = 0x44162a "mount_handle_read_buffer"
        read_count = 0
#8  0x0000000000414e6a in vshadowmount_fuse_read (path=0x209cc10 "/vss1",
    buffer=0x209cde0 "\270n\033\273\241\177", size=4096, offset=470947921920, file_info=0x7ffe74bfd1e0)
    at vshadowmount.c:352
        error = 0x0
        function = 0x441f5b "vshadowmount_fuse_read"
        path_length = 5
        read_count = 0
        result = 0
        store_index = 0
        string_index = 5
#9  0x00007fa1bb6f91a7 in fuse_fs_read_buf () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#10 0x00007fa1bb6f9352 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#11 0x00007fa1bb70181e in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#12 0x00007fa1bb70222b in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#13 0x00007fa1bb6fea6c in fuse_session_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#14 0x00007fa1bb6f71c8 in fuse_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
No symbol table info available.
#15 0x0000000000416074 in main (argc=5, argv=0x7ffe74bfd7a8) at vshadowmount.c:2320
        error = 0x0
        mount_point = 0x7ffe74bff8ab "/mnt/vssmount/"
        option_extended_options = 0x0
        option_volume_offset = 0x7ffe74bff889 "827326464"
        source = 0x7ffe74bff893 "/mnt/DFIR/win81/hdd.raw"
        program = 0x441c01 "vshadowmount"
        option = -1
        result = 1
        verbose = 0
        vshadowmount_fuse_operations = {getattr = 0x4156cc <vshadowmount_fuse_getattr>,
---Type <return> to continue, or q <return> to quit---
          readlink = 0x0, getdir = 0x0, mknod = 0x0, mkdir = 0x0, unlink = 0x0, rmdir = 0x0,
          symlink = 0x0, rename = 0x0, link = 0x0, chmod = 0x0, chown = 0x0, truncate = 0x0,
          utime = 0x0, open = 0x414a3b <vshadowmount_fuse_open>,
          read = 0x414bcb <vshadowmount_fuse_read>, write = 0x0, statfs = 0x0, flush = 0x0,
          release = 0x0, fsync = 0x0, setxattr = 0x0, getxattr = 0x0, listxattr = 0x0,
          removexattr = 0x0, opendir = 0x0, readdir = 0x4151ee <vshadowmount_fuse_readdir>,
          releasedir = 0x0, fsyncdir = 0x0, init = 0x0,
          destroy = 0x415934 <vshadowmount_fuse_destroy>, access = 0x0, create = 0x0, ftruncate = 0x0,
          fgetattr = 0x0, lock = 0x0, utimens = 0x0, bmap = 0x0, flag_nullpath_ok = 0,
          flag_nopath = 0, flag_utime_omit_ok = 0, flag_reserved = 0, ioctl = 0x0, poll = 0x0,
          write_buf = 0x0, read_buf = 0x0, flock = 0x0, fallocate = 0x0}
        vshadowmount_fuse_arguments = {argc = 0, argv = 0x0, allocated = 0}
        vshadowmount_fuse_channel = 0x209c480
        vshadowmount_fuse_handle = 0x209c4d0
(gdb) where
#0  0x00007fa1bb418935 in libcdata_btree_replace_value () from /usr/lib/libvshadow.so.1
#1  0x00007fa1bb404078 in libvshadow_block_tree_insert () from /usr/lib/libvshadow.so.1
#2  0x00007fa1bb40ae6b in libvshadow_store_descriptor_read_store_block_list ()
   from /usr/lib/libvshadow.so.1
#3  0x00007fa1bb40b56f in libvshadow_store_descriptor_read_block_descriptors ()
   from /usr/lib/libvshadow.so.1
#4  0x00007fa1bb40b87e in libvshadow_store_descriptor_read_buffer () from /usr/lib/libvshadow.so.1
#5  0x00007fa1bb40661e in libvshadow_internal_store_read_buffer_from_file_io_handle ()
   from /usr/lib/libvshadow.so.1
#6  0x00007fa1bb40676d in libvshadow_store_read_buffer () from /usr/lib/libvshadow.so.1
#7  0x0000000000414562 in mount_handle_read_buffer (mount_handle=0x209c060, store_index=0,
    buffer=0x209cde0 "\270n\033\273\241\177", size=4096, error=0x7ffe74bfd0b8) at mount_handle.c:585
#8  0x0000000000414e6a in vshadowmount_fuse_read (path=0x209cc10 "/vss1",
    buffer=0x209cde0 "\270n\033\273\241\177", size=4096, offset=470947921920, file_info=0x7ffe74bfd1e0)
    at vshadowmount.c:352
#9  0x00007fa1bb6f91a7 in fuse_fs_read_buf () from /lib/x86_64-linux-gnu/libfuse.so.2
#10 0x00007fa1bb6f9352 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#11 0x00007fa1bb70181e in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#12 0x00007fa1bb70222b in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#13 0x00007fa1bb6fea6c in fuse_session_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#14 0x00007fa1bb6f71c8 in fuse_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#15 0x0000000000416074 in main (argc=5, argv=0x7ffe74bfd7a8) at vshadowmount.c:2320
(gdb) quit
root@siftotron:/mnt/DFIR/win81# exit
exit
```

**Comment by joachimmetz** [comment]
Thanks for the report, when time permits I'll see if I can reproduce this and determine the root cause.

**Comment by joachimmetz** [comment]
Thanks to patch by @zindorsky this has been fixed.
